spring:
  #  mvc:
  #    problemdetails:
  #      enabled: true
  datasource:
    #    url: jdbc:h2:mem:coursedb
    #    driver-class-name: org.h2.Driver
    #    username: sa
    #    password: password
    url: jdbc:postgresql://localhost:5442/my_springboot_db?ApplicationName=myspringboot
    username: myspringboot
    password: myspringboot
  jpa:
    #    database: h2
    #    database-platform: org.hibernate.dialect.H2Dialect
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true # this created table on base of entity
    open-in-view: false
  #    hibernate:
  #      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: "/apidoc"

server:
  port: 8081
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: health, prometheus

resilience4j:
  circuitbreaker:
    instances:
      courses-circuit-breaker:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        maxWaitDurationInHalfOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 5
        minimumNumberOfCalls: 5
        slidingWindowSize: 20
        slidingWindowType: COUNT_BASED
        automaticTransitionFromOpenToHalfOpenEnabled: true
