spring:
  datasource:
    url: jdbc:h2:mem:coursedb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console

